# GitGuardian Configuration
# https://docs.gitguardian.com/internal-repositories-monitoring/integrations/git_hooks/pre_commit#configuration

version: 2

# Ignore test files - they contain mock/example UUIDs and tokens
paths-ignore:
  - "**/src/test/**"
  - "**/*Test.java"
  - "**/test/**"

# Additional patterns to ignore
matches-ignore:
  # Test UUID constants that look like real UUIDs
  - name: Test UUID Constants
    match: "550e8400-e29b-41d4-a716-446655440000"
  - name: Test UUID Constants 2
    match: "550e8400-e29b-41d4-a716-446655440001"
  - name: Generic Test UUIDs
    match: "00000000-0000-0000-0000-000000000001"
  - name: Generic Test UUIDs 2
    match: "00000000-0000-0000-0000-000000000002"
