# AuthHub Application Configuration

# JWT 토큰 설정
auth:
  jwt:
    # Access Token 유효 기간 (기본값: 15분)
    access-token-validity: 15m
    # Refresh Token 유효 기간 (기본값: 7일)
    refresh-token-validity: 7d

# AuthHub 내부 설정
authhub:
  blacklist:
    cleanup:
      # 배치 정리 시 한 번에 조회할 최대 토큰 개수 (기본값: 1000)
      # 운영 환경의 부하에 따라 조절 가능 (권장: 500-2000)
      batch-size: 1000
