# ===============================================
# Persistence MySQL Adapter Configuration
# ===============================================
# MySQL/JPA/Flyway 설정
# Redis 설정은 persistence-redis 모듈의 redis.yml 참조

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:authhub}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${DB_USER:root}
    password: ${DB_PASSWORD}

    hikari:
      # ===========================================
      # Pool Size Configuration
      # ===========================================
      # maximum-pool-size: 최대 동시 커넥션 수
      # - 공식: connections = (core_count * 2) + effective_spindle_count
      # - 일반적으로 10~20이 적절, 너무 크면 컨텍스트 스위칭 오버헤드 발생
      maximum-pool-size: 20
      # minimum-idle: 유휴 상태로 유지할 최소 커넥션 수
      # - maximum-pool-size와 동일하게 설정하면 고정 풀 크기 (권장)
      minimum-idle: 10

      # ===========================================
      # Timeout Configuration
      # ===========================================
      # connection-timeout: 풀에서 커넥션을 얻기 위해 대기하는 최대 시간 (ms)
      # - 너무 길면 장애 시 스레드 블로킹, 너무 짧으면 불필요한 실패
      connection-timeout: 30000
      # idle-timeout: 유휴 커넥션이 풀에서 제거되기까지의 시간 (ms)
      # - minimum-idle 이상의 커넥션에만 적용
      idle-timeout: 600000
      # max-lifetime: 커넥션의 최대 수명 (ms)
      # - MySQL wait_timeout(기본 8시간)보다 짧게 설정 권장
      # - 30분(1800000)이 일반적, DB 타임아웃보다 2~3분 짧게
      max-lifetime: 1800000
      # keepalive-time: 커넥션 유지를 위한 ping 주기 (ms)
      # - max-lifetime보다 짧아야 함, 유휴 커넥션 검증용
      keepalive-time: 300000
      # validation-timeout: 커넥션 유효성 검사 최대 시간 (ms)
      # - connection-timeout보다 짧아야 함
      validation-timeout: 5000

      # ===========================================
      # Leak Detection
      # ===========================================
      # leak-detection-threshold: 커넥션 누수 감지 임계값 (ms)
      # - 0이면 비활성화, 개발/스테이징에서 사용 권장
      # - 프로덕션에서는 성능 영향 고려 필요
      leak-detection-threshold: 60000

      # ===========================================
      # Pool Identification
      # ===========================================
      pool-name: FileFlowHikariPool

      # ===========================================
      # Connection Initialization
      # ===========================================
      # 커넥션 생성 시 실행할 SQL (유효성 검증 겸용)
      connection-init-sql: SELECT 1

      # ===========================================
      # MySQL Driver Optimization (data-source-properties)
      # ===========================================
      data-source-properties:
        # --- Prepared Statement 캐싱 ---
        # cachePrepStmts: PreparedStatement 캐싱 활성화
        cachePrepStmts: true
        # prepStmtCacheSize: 캐시할 PreparedStatement 개수 (기본 25, 권장 250~500)
        prepStmtCacheSize: 250
        # prepStmtCacheSqlLimit: 캐시할 SQL 최대 길이 (기본 256, 권장 2048)
        prepStmtCacheSqlLimit: 2048
        # useServerPrepStmts: 서버 측 Prepared Statement 사용 (성능 향상)
        useServerPrepStmts: true

        # --- Batch 최적화 ---
        # rewriteBatchedStatements: INSERT를 multi-value로 재작성 (대량 삽입 시 성능 대폭 향상)
        rewriteBatchedStatements: true

        # --- 메타데이터 캐싱 ---
        # cacheResultSetMetadata: ResultSet 메타데이터 캐시
        cacheResultSetMetadata: true
        # cacheServerConfiguration: 서버 설정 캐시 (커넥션당 1회만 조회)
        cacheServerConfiguration: true

        # --- 세션 상태 최적화 ---
        # useLocalSessionState: 세션 상태(autocommit 등) 로컬 캐시
        useLocalSessionState: true
        # elideSetAutoCommits: 동일한 autocommit 값이면 SET 요청 생략
        elideSetAutoCommits: true

        # --- 기타 최적화 ---
        # maintainTimeStats: JDBC 내부 통계 수집 비활성화 (약간의 성능 향상)
        maintainTimeStats: false

        # --- 소켓 타임아웃 ---
        # socketTimeout: 쿼리 실행 후 응답 대기 최대 시간 (ms)
        # - 장시간 쿼리나 네트워크 문제 시 무한 대기 방지
        socketTimeout: 30000
        # connectTimeout: 소켓 연결 타임아웃 (ms)
        connectTimeout: 10000

  jpa:
    # OSIV 비활성화 (필수!)
    open-in-view: false

    hibernate:
      # Flyway가 스키마 관리, Hibernate는 검증만
      ddl-auto: validate

    properties:
      hibernate:
        # SQL 포매팅 (운영 환경에서는 false)
        format_sql: false
        use_sql_comments: false

        # Batch Processing
        jdbc:
          batch_size: 50
          fetch_size: 50
        order_inserts: true
        order_updates: true
        batch_versioned_data: true

        # Query Plan Cache
        query:
          plan_cache_max_size: 2048
          in_clause_parameter_padding: true

    # SQL 로그 (Logback 사용, show-sql 비활성화)
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false

logging:
  level:
    com.ryuqq.authhub: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
