# ============================================================
# Persistence Layer Stage 환경 설정
# ============================================================
# 활성화: spring.profiles.active=stage
# ⚠️ 모든 민감 정보는 환경 변수로 관리
# ============================================================

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME}?useSSL=true&requireSSL=true&verifyServerCertificate=false&serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASSWORD}

    hikari:
      # Pool Size (Stage: Prod보다 작게)
      maximum-pool-size: 10
      minimum-idle: 5

      # Timeout
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

      # Leak Detection (Stage: 활성화)
      leak-detection-threshold: 60000

      pool-name: HikariPool-Stage

      # Connection Health Check
      connection-init-sql: SELECT 1

      # MySQL 최적화
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

  jpa:
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false

  flyway:
    # ⚠️ Stage에서도 clean 절대 금지
    clean-disabled: true

logging:
  level:
    com.ryuqq: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: DEBUG
